% 本目录下的脚本用于生成make_CFSR所需的标准nc文件
% ==============================================
% 主要步骤为：
% 打开download_CFSR_daily.m文件，设置好以下参数：
% Ymin=2014;
% Ymax=2014;
% Mmin=2;
% Mmax=2;
% NCEP_dir='F:\NCEP\';
% Output_dir='F:\NCEP\Out\';
% Yorig=2000;
% ===============================================
%如果无法读取grib2文件，则在以上m文件中，打开
% setup_nctoolbox %将NCTOOLbox添加到matlab路径
% ================================================
%执行本文档需要有nctoolbox
%网址：https://yunpan.cn/cvRR9UHaPZa6R  访问密码 cec6
%==================================================
%将make_mask整合到了download_CFSR_daily.m中，运行过程中自动生成一个Land_cover_1land_2sea.nc文件

% grib2中所包含的变量：
{'depth_below_surface_layer_bounds'
    'depth_below_surface_layer1_bounds'
    'time_bounds'
    'Temperature_surface'
    'Temperature_height_above_ground'
    'Temperature_hybrid'
    'Temperature_depth_below_surface_layer'
    'Temperature_low_cloud_top_0_Hour_Average'
    'Temperature_middle_cloud_top_0_Hour_Average'
    'Temperature_high_cloud_top_0_Hour_Average'
    'Maximum_temperature_height_above_ground_0_Hour_Interval'
    'Minimum_temperature_height_above_ground_0_Hour_Interval'
    'Latent_heat_net_flux_surface'
    'Latent_heat_net_flux_surface_0_Hour_Average'
    'Sensible_heat_net_flux_surface'
    'Sensible_heat_net_flux_surface_0_Hour_Average'
    'Snow_Phase_Change_Heat_Flux_surface_0_Hour_Average'
    'Specific_humidity_height_above_ground'
    'Specific_humidity_hybrid'
    'Precipitable_water_entire_atmosphere'
    'Precipitation_rate_surface_0_Hour_Average'
    'Snow_depth_surface'
    'Water_equivalent_of_accumulated_snow_depth_surface'
    'Categorical_Rain_surface'
    'Convective_Precipitation_Rate_surface_0_Hour_Average'
    'Potential_Evaporation_Rate_surface'
    'Potential_Evaporation_Rate_surface_0_Hour_Average'
    'Snow_Cover_surface_0_Hour_Average'
    'Sublimation_evaporation_from_snow_surface_0_Hour_Average'
    'Maximum_specific_humidity_at_2m_height_above_ground_0_Hour_Interval'
    'Minimum_specific_humidity_at_2m_height_above_ground_0_Hour_Interval'
    'u-component_of_wind_height_above_ground'
    'u-component_of_wind_hybrid'
    'v-component_of_wind_height_above_ground'
    'v-component_of_wind_hybrid'
    'Momentum_flux_u-component_surface_0_Hour_Average'
    'Momentum_flux_v-component_surface_0_Hour_Average'
    'Frictional_Velocity_surface'
    'Pressure_surface'
    'Pressure_low_cloud_bottom_0_Hour_Average'
    'Pressure_low_cloud_top_0_Hour_Average'
    'Pressure_middle_cloud_bottom_0_Hour_Average'
    'Pressure_middle_cloud_top_0_Hour_Average'
    'Pressure_high_cloud_bottom_0_Hour_Average'
    'Pressure_high_cloud_top_0_Hour_Average'
    'Geopotential_height_surface'
    'Geopotential_height_hybrid'
    'Zonal_Flux_of_Gravity_Wave_Stress_surface_0_Hour_Average'
    'Meridional_Flux_of_Gravity_Wave_Stress_surface_0_Hour_Average'
    'Planetary_Boundary_Layer_Height_surface'
    'Downward_Short-Wave_Radiation_Flux_surface'
    'Downward_Short-Wave_Radiation_Flux_surface_0_Hour_Average'
    'Downward_Short-Wave_Radiation_Flux_atmosphere_top_0_Hour_Average'
    'Upward_Short-Wave_Radiation_Flux_surface'
    'Upward_Short-Wave_Radiation_Flux_surface_0_Hour_Average'
    'Upward_Short-Wave_Radiation_Flux_atmosphere_top_0_Hour_Average'
    'UV-B_Downward_Solar_Flux_surface_0_Hour_Average'
    'Clear_sky_UV-B_Downward_Solar_Flux_surface_0_Hour_Average'
    'Clear_Sky_Downward_Solar_Flux_surface_0_Hour_Average'
    'Clear_Sky_Upward_Solar_Flux_surface_0_Hour_Average'
    'Clear_Sky_Upward_Solar_Flux_atmosphere_top_0_Hour_Average'
    'Downward_Long-Wave_Radp_Flux_surface'
    'Downward_Long-Wave_Radp_Flux_surface_0_Hour_Average'
    'Upward_Long-Wave_Radp_Flux_surface'
    'Upward_Long-Wave_Radp_Flux_surface_0_Hour_Average'
    'Upward_Long-Wave_Radp_Flux_atmosphere_top_0_Hour_Average'
    'Clear_Sky_Upward_Long_Wave_Flux_surface_0_Hour_Average'
    'Clear_Sky_Upward_Long_Wave_Flux_atmosphere_top_0_Hour_Average'
    'Clear_Sky_Downward_Long_Wave_Flux_surface_0_Hour_Average'
    'Total_cloud_cover_entire_atmosphere_0_Hour_Average'
    'Total_cloud_cover_boundary_layer_cloud_0_Hour_Average'
    'Total_cloud_cover_low_cloud_0_Hour_Average'
    'Total_cloud_cover_middle_cloud_0_Hour_Average'
    'Total_cloud_cover_high_cloud_0_Hour_Average'
    'Total_cloud_cover_convective_cloud'
    'Cloud_Work_Function_entire_atmosphere_0_Hour_Average'
    'Albedo_surface_0_Hour_Average'
    'Storm_Surface_Runoff_surface_0_Hour_Accumulation'
    'Land_cover_0__sea_1__land_surface'
    'Surface_roughness_surface'
    'Soil_moisture_content_depth_below_surface_layer'
    'Vegetation_surface'
    'Water_runoff_surface_0_Hour_Accumulation'
    'Volumetric_Soil_Moisture_Content_depth_below_surface_layer'
    'Ground_Heat_Flux_surface'
    'Ground_Heat_Flux_surface_0_Hour_Average'
    'Exchange_Coefficient_surface'
    'Plant_Canopy_Surface_Water_surface'
    'Vegetation_Type_surface'
    'Surface_exchange_coefficients_for_T_and_Q_divided_by_delta_z_surface_0_Hour_Average'
    'Surface_exchange_coefficients_for_U_and_V_divided_by_delta_z_surface_0_Hour_Average'
    'Vegetation_canopy_temperature_surface'
    'Soil_type_surface'
    'Liquid_Volumetric_Soil_Moisture_non_Frozen_depth_below_surface_layer'
    'Surface_Slope_Type_surface'
    'Direct_evaporation_from_bare_soil_surface_0_Hour_Average'
    'Ice_cover_surface'
    'Ice_thickness_surface'
    'lat'
    'lon'
    'hybrid'
    'height_above_ground'
    'depth_below_surface_layer'
    'depth_below_surface_layer1'
    'height_above_ground1'
    'time'
    'time1'};
